### ISSUE TITLE
DriveProcess fails to handle None messages from WebServer

### ISSUE THREAD

**Issue by ausshir** [UofSSpaceTeam/roveberrypy#80]
See log below:

```root                : INFO     Enabled modules:
root                : INFO     ('DriveProcess', 'USBServer', 'WebServer')
root                : INFO     Registering process subscribers...
root                : INFO     STARTING: ['DriveProcess', 'USBServer', 'WebServer']
root                : INFO     WATCHDOG: Monitoring for hanging RoverRrocess instances
StateManager        : DEBUG    Watchdog: Timer 0 Watching {}
Web Templates Loaded From: ['./WebUI/views']
StateManager        : DEBUG    Watchdog: Timer 0 Watching {'WebServer': True, 'DriveProcess': True}
USBServer           : DEBUG    b'\x02\x08$wheelRM{\xd8\x03'
DriveProcess        : DEBUG    0
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/home/pi/roveberrypy/roverprocess/RoverProcess.py", line 59, in run
    getattr(self._parent, "on_" + message.key)(message.data)
  File "/home/pi/roveberrypy/roverprocess/DriveProcess.py", line 51, in on_joystick2
    y_axis = (y_axis * 40000/2)
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'

```

This is run on the dev branch on the real rover. Can be fixed by explicitly checking for None messages (is this a hack?).

**Comment by ottopasuuna** [comment]
The issue is likely caused due to windows vs linux differences in gamepad drivers causing inconsistant axes enumeration. I don't think checking for None is a hack, we'll have to just make sure to do this when we get messages from the webui. I'll open an issue from on the webui repo and we may have to check for operating system version and change axes layout accordingly.
